<a href="https://colab.research.google.com/github/dydgus4979/ITDA_YH/blob/main/numpy_fcac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

배열 구조

In [ ]:
from numpy.core.memmap import dtype
import numpy as np

li1 =[1,2,3,4,'a','b']
print(li1, type(li1))
print(li1[0])

ar1 =np.array([[1,2,3,4,'a','b']])
print(ar1,type(ar1))
print(type(ar1.dtype))

[1, 2, 3, 4, 'a', 'b'] <class 'list'>
1
[['1' '2' '3' '4' 'a' 'b']] <class 'numpy.ndarray'>
<class 'numpy.dtype[str_]'>


내부배열 내 원소 갯수가 모두 같아야함

넘파이 객체의 속성


In [ ]:
ar3 = np.array([1,2,3,4,5]) #1행 5열
print(ar3)

print(ar3.shape)
print(ar3.ndim)

#2행 3열
ar4 = np.array([[1,1,3],[0.,1.,2.]])

print(ar4)
print(ar4.shape)
print(ar4.dtype)

[1 2 3 4 5]
(5,)
1
[[1. 1. 3.]
 [0. 1. 2.]]
(2, 3)
float64


In [ ]:
import numpy as np
arr1 = np.array([[2,3],[5,2]])
print(arr1)

[[2 3]
 [5 2]]


In [ ]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6],[7,8,9,10,11]])

print(arr2) #3행 5열

print(arr2.ndim)    #2차원
print(arr2.dtype)   #배열의 요소는 정수형

print(arr2[1][2])   #2행 3열 결과 => 4 출력

print(arr2[1:,3:])

[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 7  8  9 10 11]]
2
int64
4
[[ 5  6]
 [10 11]]


shape : 배열의 크기 알아내기

In [ ]:
arr3 = np.array([2,3,4,5,6])    #1행 5열

print(arr3)
print(arr3.shape)   #(5,)

arr4 = np.array([[1,2,3,4],[5,6,7,8]])  #2*4
print(arr4)
print(arr4.shape)

[2 3 4 5 6]
(5,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


dtype : 배열의 원소 유형 확인

In [ ]:
arr5 = np.array(['a','b','c'])
print(arr5.dtype)   #<U1

arr6 = np.array([1.0,2,4])
print(arr6.dtype)



<U1
float64


실습 2차원의 각 차원의 길이가 3인 배열 1행 값 1,2,3,4 2행값 5,6,7,8
shape, ndim, dtype, size, type 출력

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print(type(a))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
int64
8
<class 'numpy.ndarray'>


넘파이 함수


In [ ]:
ar1 = np.arange(1,5)  #1부터 4까지
print(ar1)
print(ar1.dtype)
print(ar1.astype('float64'))
print(ar1.astype('int64'))

[1 2 3 4]
int64
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:

arr2 = np.zeros((2,10)) #2행 10열인 배열, 각원소가 0으로 출력
print(arr2,arr2.dtype)

arr3 =  np.zeros((2,10), dtype='i')
print(arr3, arr3.dtype)

arr4 = np.ones((2,10))
print(arr4, arr4.dtype)

#2이상 10미만의 원소로 이루어진 1차원 배열 만들기
arr5 = np.arange(2.1,10,2)
print(arr5)

arr6 = np.ones((2,3))
print(arr6)
arr7 = np.transpose(arr6)
print(arr7)

arr8 = np.array([[1,2,3],[4,5,6]])
print(arr8)
arr9 = np.transpose(arr8)
print(arr9)

#변수명 arr1 0부터 14까지 원소로 이루어진 2차원 배열 만들기 (3행 5열)

arr =  np.arange(0,15).reshape((3,5))   #shape : 배열의 각 차원의 크기를 튜플 형태
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] float64
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] int32
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] float64
[2.1 4.1 6.1 8.1]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


배열의 사칙연산

In [ ]:
#리스트(+,*)
li3 = [1,2,3,4]
li4 = [5,6,7,8]

print(li3 + li4)
print(li3 *3)

#넘파이 배열의 사칙연산
np_1 = np.array([[1,2,3],[4,5,6]])
np_2 = np.array([[11,22,33],[10,20,30]])
print(np_1)
print(np_2)
print(np_1+np_2)

print(np_1*np_2)
print(np_2/np_1)
print(np_2-np_1)

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [10 20 30]]
[[12 24 36]
 [14 25 36]]
[[ 11  44  99]
 [ 40 100 180]]
[[11.  11.  11. ]
 [ 2.5  4.   5. ]]
[[10 20 30]
 [ 6 15 24]]


브로드캐스팅 : 크기가 서로다른 배열끼리 더하기
(행, 열 중에 하나라도 같아야함 가능함)

In [ ]:
br_ar = np.array([100,200,300]) #1행 3열
print(br_ar.shape)

np_1 = np.array([[1,2,3],[4,5,6]])  #2행 3열
print(np_1.shape)

print(br_ar + np_1) #np_1[0] + np_1[1]에 각각 더해짐

(3,)
(2, 3)
[[101 202 303]
 [104 205 306]]


In [ ]:
#브로드캐스팅이 안되는 경우
np_1 = np.array([[1,2,3],[4,5,6]])  #2행 3열
br_ar2 = np.array([1,2,3,4,5,6,7,8,9])
#print(np_1+br_ar2) #행과 열의 크기가 모두 다 다른 배열은 더할 수 없다

판다스
시리즈


In [ ]:
#기본구조
import pandas as pd

s = pd.Series(['python',2022,9,23],index = ['a','b','c','d'],name = 'example')
print(s)



a    python
b      2022
c         9
d        23
Name: example, dtype: object


딕셔너리->시리즈 변환

In [ ]:
import pandas as pd
dict_data = {'서울':1,'경기':2,'강원':3}
sr = pd.Series(dict_data)
print(sr,type(sr))  

#인덱스 배열 선택
print(sr.index) #타입 strind을 object로 본다

#데이터 값 배열 선택
print(sr.values)

#자료형
print(sr.dtype)


서울    1
경기    2
강원    3
dtype: int64 <class 'pandas.core.series.Series'>
Index(['서울', '경기', '강원'], dtype='object')
[1 2 3]
int64


In [ ]:
#인덱스를 지정해서 변환
dict_data1 = pd.Series(dict_data, index=['a','b','c'])  #키값이 달라서 키값으로 못가져오기 때문
print(dict_data)    #values 값이 NaN으로 출력

dict_data2 = pd.Series(dict_data, index=['서울','경기','강원']) #키값을 정확히 입력하면
print(dict_data2)#values 값을 잘 받아옴

리스트 -> 시리즈 변환


In [ ]:
li_data = ['2022',9.23,'python',100,True]
sr = pd.Series(li_data)
print(sr,'\n')

idx = sr.index
print(idx)
val = sr.values
print(val,'\n')

#인덱스 지정해서 변환
li_data1 = pd.Series(li_data, index = [1,2,3,4,5])
print(li_data1)

0      2022
1      9.23
2    python
3       100
4      True
dtype: object 

RangeIndex(start=0, stop=5, step=1)
['2022' 9.23 'python' 100 True] 

1      2022
2      9.23
3    python
4       100
5      True
dtype: object


튜플 -> 시리즈 변환


In [ ]:
t_data = ('python','2022-09-23',True)
sr = pd.Series(t_data, index = ['과목','날짜','수강여부'])
print(sr)

#원소 선택(2가지 방법)
#방법1 : 정수형 위치 인덱스 사용 :  리스트 와 같은 원리 
print(sr[0])

#방법2 : 인덱스 이름을 사용 : 딕셔너리와 같은 원리
print(sr['과목'])

#여러값을 인덱싱
print(sr[[1,2]],'\n')
print(sr[['과목','날짜']],'\n')
print(sr[0:2])  #슬라이싱으로 인덱싱 할 때는 대괄호 하나만 사용함


과목          python
날짜      2022-09-23
수강여부          True
dtype: object
python
python
날짜      2022-09-23
수강여부          True
dtype: object 

과목        python
날짜    2022-09-23
dtype: object 

과목        python
날짜    2022-09-23
dtype: object


시리즈 -> 딕셔너리 또는 리스트

In [ ]:
s_dict =dict(dict_data)
print(s_dict)

s_list = list(dict_data)
print(s_list)

{'서울': 1, '경기': 2, '강원': 3}
['서울', '경기', '강원']


시리즈 -> 딕셔너리 또는 리스트

In [ ]:
#수정
#dict_data = {'서울':1,'경기':2,'강원':3}
#li_data = ['2022',9.23,'python',100,True]
dict_data['서울'] = 30
print(dict_data)

li_data[1] = 5
print(li_data)

#추가
dict_data['부산']=4
print(dict_data)

#위치 인덱스 에러 발생 -> IndexError: list assignment index out of range
#li_data[5]=50   
#print(li_data)

#삭제
del dict_data['부산']
print(dict_data)

dict_data.pop('경기')
print(dict_data)

{'서울': 30, '경기': 2, '강원': 3}
['2022', 5, 'python', 100, True]
{'서울': 30, '경기': 2, '강원': 3, '부산': 4}
{'서울': 30, '경기': 2, '강원': 3}
{'서울': 30, '강원': 3}


데이터프레임

In [ ]:
import pandas as pd

values = [[1,2,3],[4,5,6],[7,8,9]]
index = ['one','two','three']
columns = ['A','B','C']

df = pd.DataFrame(values, index=index,columns=columns)
print(df,'\n')

       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9 



딕셔너리 -> 데이터프레임

In [ ]:
data_dict = {'name':['짱구','철수','유리','맹구'], 'score' : [57.5,91.3,86.6,77.5]}
df1 = pd.DataFrame(data_dict)
print(df1)

  name  score
0   짱구   57.5
1   철수   91.3
2   유리   86.6
3   맹구   77.5


리스트->데이터프레임

In [ ]:
values = [[1,2,3],[4,5,6],[7,8,9]]
index = ['one','two','three']
columns = ['A','B','c']

df2 = pd.DataFrame(values,index =index,columns =columns  )
print(df2)
print(df2.index)
print(df2.columns)

df2.index = ['일','이','삼']
print(df2)

df.columns = []


       A  B  c
one    1  2  3
two    4  5  6
three  7  8  9
Index(['one', 'two', 'three'], dtype='object')
Index(['A', 'B', 'c'], dtype='object')
   A  B  c
일  1  2  3
이  4  5  6
삼  7  8  9


A  B  C
one    1  2  3
two    4  5  6
three  7  8  9

In [ ]:
#df3 출력 .index columnsc 출력
data_li = [['100','짱구',70.5],['1001','철수',90.3],['1002','훈이',81.3],['1003','맹구',78.9]]

df3 = pd.DataFrame(data_li)

print(df3,'\n')
print(df3.index)
print(df3.columns)

#columns 지정 '학번',이름 점수
df4 = pd.DataFrame(data_li,columns=['학번','이름','점수'])
print(df4)

      0   1     2
0   100  짱구  70.5
1  1001  철수  90.3
2  1002  훈이  81.3
3  1003  맹구  78.9 

RangeIndex(start=0, stop=4, step=1)
RangeIndex(start=0, stop=3, step=1)
     학번  이름    점수
0   100  짱구  70.5
1  1001  철수  90.3
2  1002  훈이  81.3
3  1003  맹구  78.9


데이터프레임 -> 리스트

In [ ]:
s= {'name':['짱구','철수','유리','맹구'],'score' : [57.5,91.3,86.6,77.5]}
print(type(s))

df_l1 = pd.DataFrame(s, columns = ['name','score'])
print(df_l1)

st_list = df_l1.values.tolist()
print(st_list, type(st_list))

#컬럼과 값을 함께 리스틀로 변환하는 방법
#item_list =df_l1.colunms.values.tolist()+df_l1.values.tolist()
#print(item_list)

#특정 값만 리스트로 변환하는 방법
item_list=df_l1['name'].values.tolist()
print(item_list)
item_list.append('훈이')
print(item_list)

<class 'dict'>
  name  score
0   짱구   57.5
1   철수   91.3
2   유리   86.6
3   맹구   77.5
[['짱구', 57.5], ['철수', 91.3], ['유리', 86.6], ['맹구', 77.5]] <class 'list'>
['짱구', '철수', '유리', '맹구']
['짱구', '철수', '유리', '맹구', '훈이']
